### ISSUE TITLE
EADDRINUSE when grunt-apimocker started again.

### ISSUE THREAD

**Issue by barquehk** [gstroup/grunt-apimocker#2]
I am integrating grunt-apimocker with a yeoman man scaffolded angular project. I added the apimocker config file to the watcher's list. The idea is once the config file is changed, the watcher will run an associated grunt task again. 

However, when I actually change the config file during run-time. The console has the following error message printed out "EADDRINUSE". I suspected the last apimocker server hasn't been terminated properly causing this error message.

```
Running "apimocker" task
Starting apimocker server
Loading config file: /apimocker.json
Set route: GET first : king.json 20 ms
Set route: GET service/instance : instance/instance.json 500 ms
Mock server listening on port 7878
Fatal error: listen EADDRINUSE
```

Is there any method to turn down the last apimocker properly in my situation?

**Comment by gstroup** [comment]
I like the way you've added the apimocker config file to the watcher's list.  That's a good idea that I hadn't considered before.  This grunt-apimocker plugin is rather simplistic... it does not spawn the apimocker server in a separate thread.  I'd have to do some research into that.

But apimocker does have a simple API to reload the config file without restarting the apimocker server.  You can make an HTTP GET call to the apimocker server, like this:  [http://localhost:7878/admin/reload](http://localhost:7878/admin/reload)

Could you possibly do this from grunt using the grunt-http plugin?

I haven't had time lately to work this plugin, but pull requests are definitely welcome!

**Comment by gstroup** [comment]
Also, take a look at issue #1.  I think @snyoz got this working with the watch task...

**Comment by barquehk** [comment]
wow, grunt-http  works.

Config for grunt-http

```
  // config for grunt-http
    http:{
      apimocker:{
        options:{
          url: 'http://localhost:7878/admin/reload',
          method: 'GET'
        }
      }
    },
```

Config for grunt-watch

```
    watch:{
      apimocker:{
        files:['apimocker.json'],
        tasks:['http:apimocker']
      }
    },
```

Thanks!

**Comment by gstroup** [comment]
Excellent!  Glad that worked for you. And thanks for sharing your Grunt configuration.
